### ISSUE TITLE
[Bug] The patient can be assigned to a task with exact same dates

### ISSUE THREAD

**Issue by HUANGXUANKUN** [AY1920S1-CS2113-T13-2/main#155]
**Summary**: @WEIFENG-NUSCEG The exact same eventtask/standardtask can be assigned to the same patient.

**Steps to replicate:** 

1.  Enter command `assign eventtask #3 1 27/12/2020 1640 to 27/12/2021 1640`
2.  Repeat step 1

**Expected output:** Throw exception to remind user the same task with same details has already been assigned.

**Actual output**: Patient can be assigned with same task with same start_date & end_date multiple times. See attached image.

![image](https://user-images.githubusercontent.com/39436447/67287182-33908500-f50d-11e9-9981-de9d6f32b256.png)

**Comment by WEIFENG-NUSCEG** [comment]
This bug is quite hard to fix now as each patienttask is now assigned by a unique id internally, hence every patienttask will be different. The previous method to check if a patienttask exists does not work anymore. For this bug to be fixed, It requires me to check through the Datetime elements of all the patients, which will be a O(N) process. I will try to find a better way to solve this.

**Comment by WEIFENG-NUSCEG** [comment]
This bug has been fixed in pr #190
