### ISSUE TITLE
BUG : typo corrector is auto correcting without notify the user

### ISSUE THREAD

**Issue by WEIFENG-NUSCEG** [AY1920S1-CS2113-T13-2/main#243]
typo corrector is auto correcting without notify the user, and the coverage of the typo corrector is too wide.

**Comment by lmtaek** [comment]
The autocorrector seems to disable several of Dukepital's commands in the CLI due to its assumptions that they are commands for different features.

It would likely be best to lower the amount of variance in command inputs, and possibly suggest the corrected command rather than automatically implementing it.

**Comment by lmtaek** [comment]
Upon going through reported bugs, it seems as if any incorrect command was given without a `:` to indicate information fields, then the Autocorrector assumes it's a `list` command. 

Not entirely sure if this is the case, but it seems to be a consistent outcome.

**Comment by HUANGXUANKUN** [comment]
Noted. I am also concerned about the command input without ':'. 
I will make appropriate fix on this Sunday.

**Comment by lmtaek** [comment]
Resolved with #287 .
